2017-03-29 18:52:24 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /admin/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\admin\sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    if not self.has_permission(request):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\admin\sites.py", line 173, in has_permission
    return request.user.is_active and request.user.is_staff
AttributeError: 'WSGIRequest' object has no attribute 'user'
2017-03-29 18:55:57 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /admin/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\admin\sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    if not self.has_permission(request):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\admin\sites.py", line 173, in has_permission
    return request.user.is_active and request.user.is_staff
AttributeError: 'WSGIRequest' object has no attribute 'user'
2017-03-29 19:12:23 - INFO - views:login:332 - User rit2013063 successfully authenticated
2017-03-29 19:12:23 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 338, in login
    _add_user_data_to_session(user, request)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 285, in _add_user_data_to_session
    request.session['username'] = auth.get_user().get_username()
TypeError: get_user() missing 1 required positional argument: 'request'
2017-03-29 19:13:01 - WARNING - csrf:_reject:103 - Forbidden (CSRF token missing or incorrect.): /
2017-03-29 19:13:12 - INFO - views:login:332 - User rit2013063 successfully authenticated
2017-03-29 19:13:12 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 185, in user_profile
    user = _get_all_user_info(auth.get_user().get_username())
TypeError: get_user() missing 1 required positional argument: 'request'
2017-03-29 19:13:30 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 185, in user_profile
    user = _get_all_user_info(auth.get_user(request).get_username())
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 84, in _get_all_user_info
    dict['username'] = user.get_username()
AttributeError: 'str' object has no attribute 'get_username'
2017-03-29 19:13:52 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 189, in user_profile
    'layout_data' : get_layout_data(request),
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 638, in get_layout_data
    dict['unread_notifications_count'] = Notifications.objects.filter(receiver = user).filter(status = 'U').count()
NameError: name 'Notifications' is not defined
2017-03-29 19:14:26 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 189, in user_profile
    'layout_data' : get_layout_data(request),
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 638, in get_layout_data
    dict['unread_notifications_count'] = Notification.objects.filter(receiver = user).filter(status = 'U').count()
NameError: name 'Notifications' is not defined
2017-03-29 19:15:01 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 189, in user_profile
    'layout_data' : get_layout_data(request),
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 638, in get_layout_data
    dict['unread_notifications_count'] = Notification.objects.filter(receiver = user).filter(status = 'U').count()
NameError: name 'Notifications' is not defined
2017-03-29 19:15:22 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 190, in user_profile
    'user' : user
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 988, in render
    bit = node.render_annotated(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 955, in render_annotated
    return self.render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 151, in render
    compiled_parent = self.get_parent(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 148, in get_parent
    return self.find_template(parent, context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 128, in find_template
    template_name, skip=history,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:18:56 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 190, in user_profile
    'user' : user
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 988, in render
    bit = node.render_annotated(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 955, in render_annotated
    return self.render(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 151, in render
    compiled_parent = self.get_parent(context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 148, in get_parent
    return self.find_template(parent, context)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 128, in find_template
    template_name, skip=history,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:30:34 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 185, in user_profile
    user = _get_all_user_info(auth.get_user(request))
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 88, in _get_all_user_info
    _get_all_student_info(user, dict)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 113, in _get_all_student_info
    thesis = Thesis.objects.get(student = student)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 387, in get
    self.model._meta.object_name
app.models.DoesNotExist: Thesis matching query does not exist.
2017-03-29 19:33:21 - INFO - views:logout:353 - User rit2013063 successfully logged out
2017-03-29 19:33:28 - INFO - views:login:332 - User rit2013063 successfully authenticated
2017-03-29 19:36:27 - INFO - views:logout:354 - User rit2013063 successfully logged out
2017-03-29 19:36:32 - INFO - views:login:333 - User rit2013063 successfully authenticated
2017-03-29 19:36:54 - INFO - views:logout:354 - User rit2013063 successfully logged out
2017-03-29 19:36:57 - INFO - views:login:333 - User rit2013063 successfully authenticated
2017-03-29 19:37:53 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/notifications/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 401, in user_notifications
    user = auth.get_user()
TypeError: get_user() missing 1 required positional argument: 'request'
2017-03-29 19:42:26 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/notifications/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 413, in user_notifications
    'unread_notifications': unread_notifications,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1042, in do_if
    nodelist = parser.parse(('endif',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:43:00 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/notifications/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 413, in user_notifications
    'unread_notifications': unread_notifications,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1042, in do_if
    nodelist = parser.parse(('endif',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:43:23 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/notifications/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 413, in user_notifications
    'unread_notifications': unread_notifications,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1042, in do_if
    nodelist = parser.parse(('endif',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:44:12 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/abstract/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 73, in student_add_abstract
    'isAbstractApproved' : isAbstractApproved
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1042, in do_if
    nodelist = parser.parse(('endif',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:48:38 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/edit_profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 369, in user_edit_profile
    user_details = Student.objects.get(user = user)
UnboundLocalError: local variable 'user' referenced before assignment
2017-03-29 19:51:29 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/abstract/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 73, in student_add_abstract
    'isAbstractApproved' : isAbstractApproved
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1042, in do_if
    nodelist = parser.parse(('endif',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:52:24 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/synopsis/view/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 155, in student_view_synopsis
    'synopsisPath' : synopsisPath
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:53:09 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 257, in student_add_keywords
    'thesis_keywords' : thesis_keywords,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:53:31 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 257, in student_add_keywords
    'thesis_keywords' : thesis_keywords,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 267, in do_extends
    nodelist = parser.parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\loader_tags.py", line 241, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\template\smartif.py", line 201, in parse
    self.current_token.display())
django.template.exceptions.TemplateSyntaxError: Unused 'is' at end of if expression.
2017-03-29 19:53:43 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/get/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 346, in get_ieee_keywords
    parent = int(request.POST['parent'])
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'parent'"
2017-03-29 19:54:30 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/status/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 439, in student_phd_status
    thesis = Thesis.objects.get(user = user)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 378, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: abstract, id, panelmember, status, status_id, student, student_id, synopsis, thesis, thesisguide, thesisguideapproval, thesiskeyword, thesislog, title
2017-03-29 19:55:07 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/status/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 439, in student_phd_status
    thesis = Thesis.objects.get(student = user)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 378, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1174, in build_filter
    self.check_related_objects(field, value, opts)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1071, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1055, in check_query_object_type
    (value, opts.object_name))
ValueError: Cannot query "rit2013063": Must be "Student" instance.
2017-03-29 19:56:16 - INFO - views:login:333 - User rit2013063 successfully authenticated
2017-03-29 19:56:22 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/get/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 346, in get_ieee_keywords
    parent = int(request.POST['parent'])
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'parent'"
2017-03-29 19:56:36 - INFO - views:logout:354 - User rit2013063 successfully logged out
2017-03-29 20:01:39 - INFO - views:login:333 - User rit2013063 successfully authenticated
2017-03-29 20:01:50 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/get/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 346, in get_ieee_keywords
    parent = int(request.POST['parent'])
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'parent'"
2017-03-30 01:06:56 - INFO - views:login:333 - User pavan successfully authenticated
2017-03-30 01:06:56 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 339, in login
    _add_user_data_to_session(user, request)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 313, in _add_user_data_to_session
    request.session['full_name'] = first_name + ' ' + last_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2017-03-30 01:09:41 - INFO - views:login:333 - User pavan successfully authenticated
2017-03-30 01:09:41 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 339, in login
    _add_user_data_to_session(auth.get_user(request), request)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 313, in _add_user_data_to_session
    request.session['full_name'] = first_name + ' ' + last_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2017-03-30 01:35:32 - WARNING - csrf:_reject:103 - Forbidden (CSRF token missing or incorrect.): /
2017-03-30 01:35:44 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 331, in login
    auth.login(request, user)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\__init__.py", line 110, in login
    request.session.cycle_key()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\sessions\backends\base.py", line 302, in cycle_key
    self.create()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\sessions\backends\db.py", line 53, in create
    self.save(must_create=True)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\sessions\backends\db.py", line 86, in save
    obj.save(force_insert=must_create, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
2017-03-30 01:36:05 - INFO - views:login:332 - User pavan successfully authenticated
2017-03-30 01:36:05 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 338, in login
    _add_user_data_to_session(auth.get_user(request), request)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 312, in _add_user_data_to_session
    request.session['full_name'] = first_name + ' ' + last_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2017-03-30 01:40:13 - INFO - views:login:332 - User pavan successfully authenticated
2017-03-30 01:40:13 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 338, in login
    _add_user_data_to_session(auth.get_user(request), request)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 284, in _add_user_data_to_session
    type = _get_user_type(user)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 44, in _get_user_type
    if Approver.objects.filter(user = user).exists():
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: active, faculty, faculty_id, id
2017-03-30 01:41:12 - INFO - views:login:334 - User pavan successfully authenticated
2017-03-30 01:41:43 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/edit_profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 370, in user_edit_profile
    user_details = Student.objects.get(user = user)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 387, in get
    self.model._meta.object_name
app.models.DoesNotExist: Student matching query does not exist.
2017-03-30 01:43:21 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/edit_profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 370, in user_edit_profile
    user_details = Student.objects.get(user = user)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 387, in get
    self.model._meta.object_name
app.models.DoesNotExist: Student matching query does not exist.
2017-03-30 01:44:51 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 621, in search_user_query
    result = _clean_user_info_results(sorted_results)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 570, in _clean_user_info_results
    dict['email_id'] = item[0].email_id
AttributeError: 'User' object has no attribute 'email_id'
2017-03-30 01:44:51 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 621, in search_user_query
    result = _clean_user_info_results(sorted_results)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 570, in _clean_user_info_results
    dict['email_id'] = item[0].email_id
AttributeError: 'User' object has no attribute 'email_id'
2017-03-30 01:44:51 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 621, in search_user_query
    result = _clean_user_info_results(sorted_results)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 570, in _clean_user_info_results
    dict['email_id'] = item[0].email_id
AttributeError: 'User' object has no attribute 'email_id'
2017-03-30 01:44:52 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 613, in search_user_query
    for user in User.objects.filter(email_id__icontains = email):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'email_id' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 01:44:52 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 613, in search_user_query
    for user in User.objects.filter(email_id__icontains = email):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'email_id' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 01:44:52 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 613, in search_user_query
    for user in User.objects.filter(email_id__icontains = email):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'email_id' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 01:44:53 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 613, in search_user_query
    for user in User.objects.filter(email_id__icontains = email):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'email_id' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 01:44:53 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 613, in search_user_query
    for user in User.objects.filter(email_id__icontains = email):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'email_id' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 01:45:06 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 321, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 295, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 01:45:06 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 321, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 295, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 01:45:09 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/status/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 283, in guide_phd_status
    'unread_notifications' : get_unread_notifications(request.session['username']),
NameError: name 'get_unread_notifications' is not defined
2017-03-30 01:46:17 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/help/procedure/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 516, in guide_help_procedure
    'unread_notifications' : get_unread_notifications(request.session['username'])
NameError: name 'get_unread_notifications' is not defined
2017-03-30 01:46:43 - INFO - views:logout:355 - User pavan successfully logged out
2017-03-30 01:46:52 - INFO - views:login:334 - User gcnandi successfully authenticated
2017-03-30 01:49:40 - INFO - views:logout:355 - User gcnandi successfully logged out
2017-03-30 01:50:38 - INFO - views:login:334 - User gcnandi successfully authenticated
2017-03-30 01:52:50 - INFO - views:logout:355 - User gcnandi successfully logged out
2017-03-30 01:52:58 - INFO - views:login:334 - User gcnandi successfully authenticated
2017-03-30 01:58:03 - INFO - views:logout:355 - User gcnandi successfully logged out
2017-03-30 02:00:29 - INFO - views:login:334 - User basu successfully authenticated
2017-03-30 02:41:51 - INFO - views:logout:370 - User basu successfully logged out
2017-03-30 02:41:56 - INFO - views:login:349 - User basu successfully authenticated
2017-03-30 02:42:00 - INFO - views:logout:370 - User basu successfully logged out
2017-03-30 02:42:04 - INFO - views:login:349 - User rit2013063 successfully authenticated
2017-03-30 02:42:47 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/abstract/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 82, in student_add_abstract
    send_notification_to_guides(student, notification_message)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 31, in send_notification_to_guides
    send_notification(student, receiver, message, '')
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 243, in send_notification
    notification = Notifications(sender = sender, receiver = receiver, message = message, link = link, status = 'U')
NameError: name 'Notifications' is not defined
2017-03-30 02:43:13 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/abstract/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 82, in student_add_abstract
    send_notification_to_guides(student, notification_message)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 31, in send_notification_to_guides
    send_notification(student, receiver, message, '')
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 243, in send_notification
    notification = Notification(sender = sender, receiver = receiver, message = message, link = link, status = 'U')
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\base.py", line 431, in __init__
    setattr(self, field.name, rel_obj)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\fields\related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "<Student: Vamsi Sangam>": "Notification.sender" must be a "User" instance.
2017-03-30 02:45:31 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 02:45:31 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/profile/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 202, in user_profile
    user = _get_all_user_info(auth.get_user(request))
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 92, in _get_all_user_info
    _get_all_guide_info(user, dict)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 188, in _get_all_guide_info
    student = thesisGuide.thesis.user
AttributeError: 'Thesis' object has no attribute 'user'
2017-03-30 02:46:57 - INFO - views:logout:370 - User pavan successfully logged out
2017-03-30 03:22:46 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/get/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'parent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 346, in get_ieee_keywords
    parent = int(request.POST['parent'])
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'parent'"
2017-03-30 03:24:38 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/get/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 362, in get_ieee_keywords
    if parent_id != -1:
NameError: name 'parent_id' is not defined
2017-03-30 03:32:22 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/add/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\student_views.py", line 409, in student_add_keyword_to_thesis
    thesis = Thesis.objects.get(username = user)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 378, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: abstract, id, panelmember, status, status_id, student, student_id, synopsis, thesis, thesisguide, thesisguideapproval, thesiskeyword, thesislog, title
2017-03-30 03:36:24 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /student/keywords/add/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view app.student_views.student_add_keyword_to_thesis didn't return an HttpResponse object. It returned None instead.
2017-03-30 03:40:11 - INFO - views:logout:370 - User rit2013063 successfully logged out
2017-03-30 03:40:17 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 03:40:20 - INFO - views:logout:370 - User pavan successfully logged out
2017-03-30 03:40:23 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 03:40:29 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/thesis/unevaluated/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 199, in guide_unevaluated_thesis
    dict['title'] = thesis_object.title
NameError: name 'thesis_object' is not defined
2017-03-30 03:43:29 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 320, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 294, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 03:50:31 - INFO - views:logout:370 - User pavan successfully logged out
2017-03-30 03:50:35 - INFO - views:login:349 - User rit2013063 successfully authenticated
2017-03-30 03:51:08 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 03:52:05 - INFO - views:logout:370 - User pavan successfully logged out
2017-03-30 03:52:45 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 03:54:56 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/abstract/unevaluated/evaluate/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 94, in guide_evaluate_unevaluated_abstract
    send_notification_to_other_guides(user, notification_message, thesis)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 26, in send_notification_to_other_guides
    if receiver != username:
NameError: name 'username' is not defined
2017-03-30 03:54:58 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/abstract/unevaluated/evaluate/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 94, in guide_evaluate_unevaluated_abstract
    send_notification_to_other_guides(user, notification_message, thesis)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 26, in send_notification_to_other_guides
    if receiver != username:
NameError: name 'username' is not defined
2017-03-30 03:55:02 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/abstract/unevaluated/evaluate/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 94, in guide_evaluate_unevaluated_abstract
    send_notification_to_other_guides(user, notification_message, thesis)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 26, in send_notification_to_other_guides
    if receiver != username:
NameError: name 'username' is not defined
2017-03-30 03:56:46 - INFO - views:logout:370 - User pavan successfully logged out
2017-03-30 03:57:29 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 03:57:37 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/notifications/markread/1
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 537, in mark_notification_read
    if request.method == "POST" and _verify_user_notification(auth.get_user(request), id):
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 452, in _verify_user_notification
    return (notification is not None) and (notification.receiver.user == user)
AttributeError: 'User' object has no attribute 'user'
2017-03-30 03:59:10 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/notifications/markread/1
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 537, in mark_notification_read
    if request.method == "POST" and _verify_user_notification(auth.get_user(request), id):
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 452, in _verify_user_notification
    return (notification is not None) and (notification.receiver == user)
NameError: name 'user' is not defined
2017-03-30 04:01:04 - INFO - views:logout:370 - User pavan successfully logged out
2017-03-30 04:01:36 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 04:03:25 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/thesis/unevaluated/evaluate/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 234, in guide_evaluate_unevaluated_thesis
    thesisGuideApprovals = ThesisGuideApproval(thesis = thesis, guide = guide, type = 'T')
NameError: name 'guide' is not defined
2017-03-30 17:34:51 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\admin\sites.py", line 407, in login
    return login(request, **defaults)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\views.py", line 49, in inner
    return func(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\views.py", line 76, in login
    auth_login(request, form.get_user())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\__init__.py", line 108, in login
    request.session.flush()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\sessions\backends\base.py", line 293, in flush
    self.delete()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\sessions\backends\db.py", line 98, in delete
    self.model.objects.get(session_key=session_key).delete()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\base.py", line 862, in delete
    return collector.delete()
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\deletion.py", line 310, in delete
    count = query.delete_batch(pk_list, self.using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\subqueries.py", line 46, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\subqueries.py", line 28, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\compiler.py", line 852, in execute_sql
    cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
2017-03-30 22:10:02 - INFO - views:login:349 - User anshul successfully authenticated
2017-03-30 22:10:28 - INFO - views:logout:370 - User anshul successfully logged out
2017-03-30 22:10:33 - INFO - views:login:349 - User pavan successfully authenticated
2017-03-30 22:11:01 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 636, in search_user_query
    result = _clean_user_info_results(sorted_results)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 585, in _clean_user_info_results
    dict['email_id'] = item[0].email_id
AttributeError: 'User' object has no attribute 'email_id'
2017-03-30 22:12:06 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 636, in search_user_query
    result = _clean_user_info_results(sorted_results)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 586, in _clean_user_info_results
    dict['type'] = item[0].type
AttributeError: 'User' object has no attribute 'type'
2017-03-30 22:13:05 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 636, in search_user_query
    result = _clean_user_info_results(sorted_results)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 582, in _clean_user_info_results
    dict['username'] = item.username
AttributeError: 'tuple' object has no attribute 'username'
2017-03-30 22:14:55 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /user/search/query/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 631, in search_user_query
    result = _clean_user_info_results(sorted_results)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 581, in _clean_user_info_results
    dict = _get_all_user_info(user)
  File "E:\Education\GitHub Projects\PhDPortal\app\views.py", line 86, in _get_all_user_info
    dict['username'] = user.get_username()
AttributeError: 'tuple' object has no attribute 'get_username'
2017-03-30 23:00:12 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 321, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 295, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 23:00:19 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 321, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 295, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 23:02:57 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 321, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 295, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 23:04:20 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 322, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 295, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
2017-03-30 23:05:13 - ERROR - base:handle_uncaught_exception:284 - Internal Server Error: /guide/panel/referees/foreign/
Traceback (most recent call last):
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 324, in guide_get_foreign_referee_details
    return HttpResponse(json.dumps(_get_referee_details(name, 'F')), content_type = 'application/json')
  File "E:\Education\GitHub Projects\PhDPortal\app\guide_views.py", line 295, in _get_referee_details
    users = User.objects.filter(Q(user__first_name__icontains = str) | Q(user__last_name__icontains = str))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\query.py", line 808, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1243, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1263, in _add_q
    current_negated, allow_joins, split_subq)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1269, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1149, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1035, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\Education\GitHub Projects\PhDPortal\env\lib\site-packages\django\db\models\sql\query.py", line 1330, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: communicationaddress, date_joined, email, faculty, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, receiver, referee, section, sender, student, user_permissions, username, userprofile
